import sys
from PyQt5 import QtCore, QtGui, QtWidgets

#etudiants
from ajout import Ui_Form as ajoutForm
from supprimer import Ui_Form as supprimerForm
from supprimer_section import Ui_Form as supprimer_sectionForm
from supprimer_niveau import Ui_Form as supprimer_niveauForm
from supprimer_section_niveau import Ui_Form as supprimer_section_niveauForm
from modifier_adresse import Ui_Form as modifier_adresseForm
from modifier_mail import Ui_Form as modifier_mailForm
from modifier_tel import Ui_Form as modifier_telForm
from recherche_niveau import Ui_Form as recherche_niveauForm
from recherche_num_inscr import Ui_Form as recherche_numForm
from recherche_section import Ui_Form as recherche_sectionForm
from recherche_section_niveau import Ui_Form as recherche_section_niveauForm


#matiere
from ajout_matiere import Ui_Form as ajout_matiereForm
from modifier_coefficient_matiere import Ui_Form as modifier_coefficient_matiereForm
from modifier_nom_matiere import Ui_Form as modifie_nom_matiereForm
from recherche_code_matiere import Ui_Form as recherche_code_matiereForm
from recherche_section_matiere import Ui_Form as recherche_section_matiereForm
from recherche_section_semestre_matiere import Ui_Form as recherche_section_semestre_matiereForm
from supprimer_matiere import Ui_Form as supprimer_matiereForm

#note
from  ajout_note import Ui_Form as ajout_noteForm
from modifier_note import Ui_Form as modifier_noteForm
from recherche_num_inscr_note import Ui_Form as recherche_num_inscr_noteForm
from recherche_num_semestre_NOTE import Ui_Form as recherche_num_semestre_NOTEForm
from recherche_section_niveau_note import Ui_Form as recherche_section_niveau_noteForm
from supprimer_note import Ui_Form as supprimer_noteForm

#etudiant={}

class Ui_MainWindow(QtWidgets.QMainWindow):
   def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.setWindowTitle("Gestion des notes des etudiants")
        self.inst=institut
        self.resize(1060, 631)
        self.setStyleSheet("alternate-background-color: rgb(61, 85, 55);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(910, 170, 131, 131))
        self.label.setStyleSheet("background-color: rgb(137, 33, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../téléchargement.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(750, 500, 381, 71))
        self.label_3.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 150, 1071, 191))
        self.textBrowser.setStyleSheet("font: 26pt \"Bernard MT Condensed\";")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 460, 461, 61))
        self.label_2.setStyleSheet("font: 75 italic 17pt \"MS Sans Serif\";\n"
"text-decoration: underline;")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, -10, 1071, 631))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../maha.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.textBrowser.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 26))
        self.menubar.setObjectName("menubar")
        self.menuACCUEIL = QtWidgets.QMenu(self.menubar)
        self.menuACCUEIL.setObjectName("menuACCUEIL")
        self.menuGestion_des_etudiants = QtWidgets.QMenu(self.menubar)
        self.menuGestion_des_etudiants.setObjectName("menuGestion_des_etudiants")
        self.menumise_a_jour_des_etudiants = QtWidgets.QMenu(self.menuGestion_des_etudiants)
        self.menumise_a_jour_des_etudiants.setObjectName("menumise_a_jour_des_etudiants")
        self.menusupprimer_etudiant = QtWidgets.QMenu(self.menumise_a_jour_des_etudiants)
        self.menusupprimer_etudiant.setObjectName("menusupprimer_etudiant")
        self.menumodifier_etudiant = QtWidgets.QMenu(self.menumise_a_jour_des_etudiants)
        self.menumodifier_etudiant.setObjectName("menumodifier_etudiant")
        self.menurecherche_et_affichage = QtWidgets.QMenu(self.menuGestion_des_etudiants)
        self.menurecherche_et_affichage.setObjectName("menurecherche_et_affichage")
        self.menuGestion_des_matieres = QtWidgets.QMenu(self.menubar)
        self.menuGestion_des_matieres.setObjectName("menuGestion_des_matieres")
        self.menumise_a_jour = QtWidgets.QMenu(self.menuGestion_des_matieres)
        self.menumise_a_jour.setObjectName("menumise_a_jour")
        self.menumodifier_les_donn_e_d_une_matiere = QtWidgets.QMenu(self.menumise_a_jour)
        self.menumodifier_les_donn_e_d_une_matiere.setObjectName("menumodifier_les_donn_e_d_une_matiere")
        self.menurecherche_et_affichage_2 = QtWidgets.QMenu(self.menuGestion_des_matieres)
        self.menurecherche_et_affichage_2.setObjectName("menurecherche_et_affichage_2")
        self.menuGestion_des_notes = QtWidgets.QMenu(self.menubar)
        self.menuGestion_des_notes.setObjectName("menuGestion_des_notes")
        self.menumise_a_jour_2 = QtWidgets.QMenu(self.menuGestion_des_notes)
        self.menumise_a_jour_2.setObjectName("menumise_a_jour_2")
        self.menurecherche_affichage = QtWidgets.QMenu(self.menuGestion_des_notes)
        self.menurecherche_affichage.setObjectName("menurecherche_affichage")
        self.menuCalcul_et_affichage = QtWidgets.QMenu(self.menubar)
        self.menuCalcul_et_affichage.setObjectName("menuCalcul_et_affichage")
        self.menuEnreg_et_Recup_Fichiers = QtWidgets.QMenu(self.menubar)
        self.menuEnreg_et_Recup_Fichiers.setObjectName("menuEnreg_et_Recup_Fichiers")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionajouter_etudiant = QtWidgets.QAction(self)
        self.actionajouter_etudiant.setObjectName("actionajouter_etudiant")
        self.actionsuppression_etudiant_donn_e = QtWidgets.QAction(self)
        self.actionsuppression_etudiant_donn_e.setObjectName("actionsuppression_etudiant_donn_e")
        self.actionsuppression_des_etudiants_d_une_section_donn_e = QtWidgets.QAction(self)
        self.actionsuppression_des_etudiants_d_une_section_donn_e.setObjectName("actionsuppression_des_etudiants_d_une_section_donn_e")
        self.actionsuppression_des_etudiants_d_un_niveau_donn = QtWidgets.QAction(self)
        self.actionsuppression_des_etudiants_d_un_niveau_donn.setObjectName("actionsuppression_des_etudiants_d_un_niveau_donn")
        self.actionsuppression_des_etudiants_d_un_niveau_donn_et_d_une_section_donn_e = QtWidgets.QAction(self)
        self.actionsuppression_des_etudiants_d_un_niveau_donn_et_d_une_section_donn_e.setObjectName("actionsuppression_des_etudiants_d_un_niveau_donn_et_d_une_section_donn_e")
        self.actiontelephone = QtWidgets.QAction(self)
        self.actiontelephone.setObjectName("actiontelephone")
        self.actionmail = QtWidgets.QAction(self)
        self.actionmail.setObjectName("actionmail")
        self.actionadresse = QtWidgets.QAction(self)
        self.actionadresse.setObjectName("actionadresse")
        self.actioncontenu_du_dictionnaire_etudiant = QtWidgets.QAction(self)
        self.actioncontenu_du_dictionnaire_etudiant.setObjectName("actioncontenu_du_dictionnaire_etudiant")
        self.actionrecherche_par_numero_d_inscription = QtWidgets.QAction(self)
        self.actionrecherche_par_numero_d_inscription.setObjectName("actionrecherche_par_numero_d_inscription")
        self.actionrecherche_par_section = QtWidgets.QAction(self)
        self.actionrecherche_par_section.setObjectName("actionrecherche_par_section")
        self.actionrecherche_par_section_et_niveau = QtWidgets.QAction(self)
        self.actionrecherche_par_section_et_niveau.setObjectName("actionrecherche_par_section_et_niveau")
        self.actionrecherche_par_niveau = QtWidgets.QAction(self)
        self.actionrecherche_par_niveau.setObjectName("actionrecherche_par_niveau")
        self.actionajouter_une_nouvelle_matiere = QtWidgets.QAction(self)
        self.actionajouter_une_nouvelle_matiere.setObjectName("actionajouter_une_nouvelle_matiere")
        self.actionsupprimer_une_matiere = QtWidgets.QAction(self)
        self.actionsupprimer_une_matiere.setObjectName("actionsupprimer_une_matiere")
        self.actionnom = QtWidgets.QAction(self)
        self.actionnom.setObjectName("actionnom")
        self.actioncoefficient = QtWidgets.QAction(self)
        self.actioncoefficient.setObjectName("actioncoefficient")
        self.actioncontenu_du_dictionnaire_matiere = QtWidgets.QAction(self)
        self.actioncontenu_du_dictionnaire_matiere.setObjectName("actioncontenu_du_dictionnaire_matiere")
        self.actionrecherche_par_code = QtWidgets.QAction(self)
        self.actionrecherche_par_code.setObjectName("actionrecherche_par_code")
        self.actionrecherche_par_section_2 = QtWidgets.QAction(self)
        self.actionrecherche_par_section_2.setObjectName("actionrecherche_par_section_2")
        self.actionrecherche_par_semestre_et_section = QtWidgets.QAction(self)
        self.actionrecherche_par_semestre_et_section.setObjectName("actionrecherche_par_semestre_et_section")
        self.actionajouter_une_nouvelle_note = QtWidgets.QAction(self)
        self.actionajouter_une_nouvelle_note.setObjectName("actionajouter_une_nouvelle_note")
        self.actionsupprimer_une_note = QtWidgets.QAction(self)
        self.actionsupprimer_une_note.setObjectName("actionsupprimer_une_note")
        self.actionmodifier_les_donnes_d_une_note = QtWidgets.QAction(self)
        self.actionmodifier_les_donnes_d_une_note.setObjectName("actionmodifier_les_donnes_d_une_note")
        self.actioncontenu_du_dictionnaire_notes = QtWidgets.QAction(self)
        self.actioncontenu_du_dictionnaire_notes.setObjectName("actioncontenu_du_dictionnaire_notes")
        self.actionrecherche_par_numero_inscription = QtWidgets.QAction(self)
        self.actionrecherche_par_numero_inscription.setObjectName("actionrecherche_par_numero_inscription")
        self.actionrecherche_par_section_et_niveau_2 = QtWidgets.QAction(self)
        self.actionrecherche_par_section_et_niveau_2.setObjectName("actionrecherche_par_section_et_niveau_2")
        self.actionrecherche_par_numero_inscription_et_semestre = QtWidgets.QAction(self)
        self.actionrecherche_par_numero_inscription_et_semestre.setObjectName("actionrecherche_par_numero_inscription_et_semestre")
        self.actionbulletin_de_note_d_un_etudiant = QtWidgets.QAction(self)
        self.actionbulletin_de_note_d_un_etudiant.setObjectName("actionbulletin_de_note_d_un_etudiant")
        self.actionbulletin_de_note_d_un_etudiant_par_semestre = QtWidgets.QAction(self)
        self.actionbulletin_de_note_d_un_etudiant_par_semestre.setObjectName("actionbulletin_de_note_d_un_etudiant_par_semestre")
        self.actionetudiants_admis_d_une_section_donnee = QtWidgets.QAction(self)
        self.actionetudiants_admis_d_une_section_donnee.setObjectName("actionetudiants_admis_d_une_section_donnee")
        self.actionetudiants_redoublants_d_une_section_donnee = QtWidgets.QAction(self)
        self.actionetudiants_redoublants_d_une_section_donnee.setObjectName("actionetudiants_redoublants_d_une_section_donnee")
        self.actionetudiants_admis_de_l_ISIMM = QtWidgets.QAction(self)
        self.actionetudiants_admis_de_l_ISIMM.setObjectName("actionetudiants_admis_de_l_ISIMM")
        self.actionetudiants_redoublants_de_l_ISIMM = QtWidgets.QAction(self)
        self.actionetudiants_redoublants_de_l_ISIMM.setObjectName("actionetudiants_redoublants_de_l_ISIMM")
        self.actionetudiants_redoublants_d_une_section_donnee_2 = QtWidgets.QAction(self)
        self.actionetudiants_redoublants_d_une_section_donnee_2.setObjectName("actionetudiants_redoublants_d_une_section_donnee_2")
        self.actionmoyennes_des_etudiants_d_une_section_donnee = QtWidgets.QAction(self)
        self.actionmoyennes_des_etudiants_d_une_section_donnee.setObjectName("actionmoyennes_des_etudiants_d_une_section_donnee")
        self.actionenregistrement_fichier_etudiants = QtWidgets.QAction(self)
        self.actionenregistrement_fichier_etudiants.setObjectName("actionenregistrement_fichier_etudiants")
        self.actionrecuperation_fichiers_etudiants = QtWidgets.QAction(self)
        self.actionrecuperation_fichiers_etudiants.setObjectName("actionrecuperation_fichiers_etudiants")
        self.actionenregistrement_fichier_matieres = QtWidgets.QAction(self)
        self.actionenregistrement_fichier_matieres.setObjectName("actionenregistrement_fichier_matieres")
        self.actionrecuperation_fichier_matieres = QtWidgets.QAction(self)
        self.actionrecuperation_fichier_matieres.setObjectName("actionrecuperation_fichier_matieres")
        self.actionenregistrement_fichier_notes = QtWidgets.QAction(self)
        self.actionenregistrement_fichier_notes.setObjectName("actionenregistrement_fichier_notes")
        self.actionrecuperation_fichier_notes = QtWidgets.QAction(self)
        self.actionrecuperation_fichier_notes.setObjectName("actionrecuperation_fichier_notes")
        self.menusupprimer_etudiant.addAction(self.actionsuppression_etudiant_donn_e)
        self.menusupprimer_etudiant.addAction(self.actionsuppression_des_etudiants_d_une_section_donn_e)
        self.menusupprimer_etudiant.addAction(self.actionsuppression_des_etudiants_d_un_niveau_donn)
        self.menusupprimer_etudiant.addAction(self.actionsuppression_des_etudiants_d_un_niveau_donn_et_d_une_section_donn_e)
        self.menumodifier_etudiant.addAction(self.actiontelephone)
        self.menumodifier_etudiant.addAction(self.actionmail)
        self.menumodifier_etudiant.addAction(self.actionadresse)
        self.menumise_a_jour_des_etudiants.addAction(self.actionajouter_etudiant)
        self.menumise_a_jour_des_etudiants.addAction(self.menusupprimer_etudiant.menuAction())
        self.menumise_a_jour_des_etudiants.addAction(self.menumodifier_etudiant.menuAction())
        self.menurecherche_et_affichage.addAction(self.actioncontenu_du_dictionnaire_etudiant)
        self.menurecherche_et_affichage.addAction(self.actionrecherche_par_numero_d_inscription)
        self.menurecherche_et_affichage.addAction(self.actionrecherche_par_section)
        self.menurecherche_et_affichage.addAction(self.actionrecherche_par_section_et_niveau)
        self.menurecherche_et_affichage.addAction(self.actionrecherche_par_niveau)
        self.menuGestion_des_etudiants.addAction(self.menumise_a_jour_des_etudiants.menuAction())
        self.menuGestion_des_etudiants.addAction(self.menurecherche_et_affichage.menuAction())
        self.menumodifier_les_donn_e_d_une_matiere.addAction(self.actionnom)
        self.menumodifier_les_donn_e_d_une_matiere.addAction(self.actioncoefficient)
        self.menumise_a_jour.addAction(self.actionajouter_une_nouvelle_matiere)
        self.menumise_a_jour.addAction(self.actionsupprimer_une_matiere)
        self.menumise_a_jour.addAction(self.menumodifier_les_donn_e_d_une_matiere.menuAction())
        self.menurecherche_et_affichage_2.addAction(self.actioncontenu_du_dictionnaire_matiere)
        self.menurecherche_et_affichage_2.addAction(self.actionrecherche_par_code)
        self.menurecherche_et_affichage_2.addAction(self.actionrecherche_par_section_2)
        self.menurecherche_et_affichage_2.addAction(self.actionrecherche_par_semestre_et_section)
        self.menuGestion_des_matieres.addAction(self.menumise_a_jour.menuAction())
        self.menuGestion_des_matieres.addAction(self.menurecherche_et_affichage_2.menuAction())
        self.menumise_a_jour_2.addAction(self.actionajouter_une_nouvelle_note)
        self.menumise_a_jour_2.addAction(self.actionsupprimer_une_note)
        self.menumise_a_jour_2.addAction(self.actionmodifier_les_donnes_d_une_note)
        self.menurecherche_affichage.addAction(self.actioncontenu_du_dictionnaire_notes)
        self.menurecherche_affichage.addAction(self.actionrecherche_par_numero_inscription)
        self.menurecherche_affichage.addAction(self.actionrecherche_par_section_et_niveau_2)
        self.menurecherche_affichage.addAction(self.actionrecherche_par_numero_inscription_et_semestre)
        self.menuGestion_des_notes.addAction(self.menumise_a_jour_2.menuAction())
        self.menuGestion_des_notes.addAction(self.menurecherche_affichage.menuAction())
        self.menuCalcul_et_affichage.addAction(self.actionbulletin_de_note_d_un_etudiant)
        self.menuCalcul_et_affichage.addAction(self.actionbulletin_de_note_d_un_etudiant_par_semestre)
        self.menuCalcul_et_affichage.addAction(self.actionetudiants_admis_d_une_section_donnee)
        self.menuCalcul_et_affichage.addAction(self.actionetudiants_redoublants_d_une_section_donnee)
        self.menuCalcul_et_affichage.addAction(self.actionetudiants_admis_de_l_ISIMM)
        self.menuCalcul_et_affichage.addAction(self.actionetudiants_redoublants_de_l_ISIMM)
        self.menuCalcul_et_affichage.addAction(self.actionetudiants_redoublants_d_une_section_donnee_2)
        self.menuCalcul_et_affichage.addAction(self.actionmoyennes_des_etudiants_d_une_section_donnee)
        self.menuEnreg_et_Recup_Fichiers.addAction(self.actionenregistrement_fichier_etudiants)
        self.menuEnreg_et_Recup_Fichiers.addAction(self.actionrecuperation_fichiers_etudiants)
        self.menuEnreg_et_Recup_Fichiers.addAction(self.actionenregistrement_fichier_matieres)
        self.menuEnreg_et_Recup_Fichiers.addAction(self.actionrecuperation_fichier_matieres)
        self.menuEnreg_et_Recup_Fichiers.addAction(self.actionenregistrement_fichier_notes)
        self.menuEnreg_et_Recup_Fichiers.addAction(self.actionrecuperation_fichier_notes)
        self.menubar.addAction(self.menuACCUEIL.menuAction())
        self.menubar.addAction(self.menuGestion_des_etudiants.menuAction())
        self.menubar.addAction(self.menuGestion_des_matieres.menuAction())
        self.menubar.addAction(self.menuGestion_des_notes.menuAction())
        self.menubar.addAction(self.menuCalcul_et_affichage.menuAction())
        self.menubar.addAction(self.menuEnreg_et_Recup_Fichiers.menuAction())
        self.retranslateUi(self)

        #connecter les fenetres
        self.actionajouter_etudiant.triggered.connect(self.ajoutEtud)
        self.actionsuppression_etudiant_donn_e.triggered.connect(self.supprimer)
        self.actionsuppression_des_etudiants_d_une_section_donn_e.triggered.connect(self.supprimer_section)
        self.actionsuppression_des_etudiants_d_un_niveau_donn.triggered.connect(self.supprimer_niveau)
        self.actionsuppression_des_etudiants_d_un_niveau_donn_et_d_une_section_donn_e.triggered.connect(self.supprimer_section_niveau)
        self.retranslateUi(self)
        self.actiontelephone.triggered.connect(self.modifier_tel)
        self.actionadresse.triggered.connect(self.modifier_adresse)
        self.actionmail.triggered.connect(self.modifier_mail)
        self.actionrecherche_par_numero_d_inscription.triggered.connect(self.recherche_num)
        self.actionrecherche_par_section.triggered.connect(self.recherche_section)
        self.actionrecherche_par_section_et_niveau.triggered.connect(self.recherche_section_niveau)
        self.actionrecherche_par_niveau.triggered.connect(self.recherche_niveau)
        self.actionajouter_une_nouvelle_matiere.triggered.connect(self.ajout_matiere)
        self.actionsupprimer_une_matiere.triggered.connect(self.supprimer_matiere)
        self.actionnom.triggered.connect(self.modifier_nom_matiere)
        self.actioncoefficient.triggered.connect(self.modifier_coefficient_matiere)
        self.actionrecherche_par_code.triggered.connect(self.recherche_code_matiere)
        self.actionrecherche_par_section_2.triggered.connect(self.recherche_section_matiere)
        self.actionrecherche_par_semestre_et_section.triggered.connect(self.recherche_section_semestre_matiere)
        self.actionajouter_une_nouvelle_note.triggered.connect(self.ajout_note)
        self.actionmodifier_les_donnes_d_une_note.triggered.connect(self.modifier_note)
        self.actionrecherche_par_numero_inscription.triggered.connect(self.recherche_num_inscr_note)
        self.actionrecherche_par_numero_inscription_et_semestre.triggered.connect(self.rechercher_num_semestre_note)
        self.actionrecherche_par_section_et_niveau_2.triggered.connect(self.recherche_section_niveau_note)
        self.actionsupprimer_une_note.triggered.connect(self.supprimer_note)




   def retranslateUi(self,MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ANNEE UNIVERSITAIRE :2021/2022"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bernard MT Condensed\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:600; font-style:italic; color:#750000;\">MINI PROJET : GESTION DES     NOTES  DES      ETUDIANTS</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Realise par : AZOUZI MAHA"))
        self.menuACCUEIL.setTitle(_translate("MainWindow", "ACCUEIL"))
        self.menuGestion_des_etudiants.setTitle(_translate("MainWindow", "Gestion des etudiants"))
        self.menumise_a_jour_des_etudiants.setTitle(_translate("MainWindow", "mise a jour des etudiants"))
        self.menusupprimer_etudiant.setTitle(_translate("MainWindow", "supprimer etudiant"))
        self.menumodifier_etudiant.setTitle(_translate("MainWindow", "modifier etudiant"))
        self.menurecherche_et_affichage.setTitle(_translate("MainWindow", "recherche et affichage"))
        self.menuGestion_des_matieres.setTitle(_translate("MainWindow", "Gestion des matieres"))
        self.menumise_a_jour.setTitle(_translate("MainWindow", "mise a jour"))
        self.menumodifier_les_donn_e_d_une_matiere.setTitle(_translate("MainWindow", "modifier les donnée d\'une matiere"))
        self.menurecherche_et_affichage_2.setTitle(_translate("MainWindow", "recherche et affichage"))
        self.menuGestion_des_notes.setTitle(_translate("MainWindow", "Gestion des notes"))
        self.menumise_a_jour_2.setTitle(_translate("MainWindow", "mise a jour"))
        self.menurecherche_affichage.setTitle(_translate("MainWindow", "recherche , affichage"))
        self.menuCalcul_et_affichage.setTitle(_translate("MainWindow", "Calcul et affichage"))
        self.menuEnreg_et_Recup_Fichiers.setTitle(_translate("MainWindow", "Enreg.et Recup.Fichiers"))
        self.actionajouter_etudiant.setText(_translate("MainWindow", "ajouter etudiant"))
        self.actionsuppression_etudiant_donn_e.setText(_translate("MainWindow", "suppression etudiant donnée"))
        self.actionsuppression_des_etudiants_d_une_section_donn_e.setText(_translate("MainWindow", "suppression des etudiants d\'une section donnée"))
        self.actionsuppression_des_etudiants_d_un_niveau_donn.setText(_translate("MainWindow", "suppression des etudiants d\'un niveau donné"))
        self.actionsuppression_des_etudiants_d_un_niveau_donn_et_d_une_section_donn_e.setText(_translate("MainWindow", "suppression des etudiants d\'un niveau donné et d\'une section donnée"))
        self.actiontelephone.setText(_translate("MainWindow", "telephone"))
        self.actionmail.setText(_translate("MainWindow", "mail"))
        self.actionadresse.setText(_translate("MainWindow", "adresse"))
        self.actioncontenu_du_dictionnaire_etudiant.setText(_translate("MainWindow", "contenu du dictionnaire etudiant"))
        self.actionrecherche_par_numero_d_inscription.setText(_translate("MainWindow", "recherche par numero d\'inscription"))
        self.actionrecherche_par_section.setText(_translate("MainWindow", "recherche par section"))
        self.actionrecherche_par_section_et_niveau.setText(_translate("MainWindow", "recherche par section et niveau"))
        self.actionrecherche_par_niveau.setText(_translate("MainWindow", "recherche par niveau"))
        self.actionajouter_une_nouvelle_matiere.setText(_translate("MainWindow", "ajouter une nouvelle matiere"))
        self.actionsupprimer_une_matiere.setText(_translate("MainWindow", "supprimer une matiere"))
        self.actionnom.setText(_translate("MainWindow", "nom"))
        self.actioncoefficient.setText(_translate("MainWindow", "coefficient"))
        self.actioncontenu_du_dictionnaire_matiere.setText(_translate("MainWindow", "contenu du dictionnaire matiere"))
        self.actionrecherche_par_code.setText(_translate("MainWindow", "recherche par code"))
        self.actionrecherche_par_section_2.setText(_translate("MainWindow", "recherche par section"))
        self.actionrecherche_par_semestre_et_section.setText(_translate("MainWindow", "recherche par semestre et section"))
        self.actionajouter_une_nouvelle_note.setText(_translate("MainWindow", "ajouter une nouvelle note"))
        self.actionsupprimer_une_note.setText(_translate("MainWindow", "supprimer une note"))
        self.actionmodifier_les_donnes_d_une_note.setText(_translate("MainWindow", "modifier les donnes d\'une note"))
        self.actioncontenu_du_dictionnaire_notes.setText(_translate("MainWindow", "contenu du dictionnaire notes"))
        self.actionrecherche_par_numero_inscription.setText(_translate("MainWindow", "recherche par numero inscription"))
        self.actionrecherche_par_section_et_niveau_2.setText(_translate("MainWindow", "recherche par section et niveau"))
        self.actionrecherche_par_numero_inscription_et_semestre.setText(_translate("MainWindow", "recherche par numero inscription et semestre"))
        self.actionbulletin_de_note_d_un_etudiant.setText(_translate("MainWindow", "bulletin de note d\'un etudiant"))
        self.actionbulletin_de_note_d_un_etudiant_par_semestre.setText(_translate("MainWindow", "bulletin de note d\'un etudiant par semestre"))
        self.actionetudiants_admis_d_une_section_donnee.setText(_translate("MainWindow", "etudiants admis d\'une section donnee"))
        self.actionetudiants_redoublants_d_une_section_donnee.setText(_translate("MainWindow", "etudiants redoublants d\'une section donnee"))
        self.actionetudiants_admis_de_l_ISIMM.setText(_translate("MainWindow", "etudiants admis de l\'ISIMM"))
        self.actionetudiants_redoublants_de_l_ISIMM.setText(_translate("MainWindow", "etudiants redoublants de l\'ISIMM"))
        self.actionetudiants_redoublants_d_une_section_donnee_2.setText(_translate("MainWindow", "etudiants redoublants d\'une section donnee"))
        self.actionmoyennes_des_etudiants_d_une_section_donnee.setText(_translate("MainWindow", "moyennes des etudiants d\'une section donnee"))
        self.actionenregistrement_fichier_etudiants.setText(_translate("MainWindow", "enregistrement fichier etudiants"))
        self.actionrecuperation_fichiers_etudiants.setText(_translate("MainWindow", "recuperation fichiers etudiants"))
        self.actionenregistrement_fichier_matieres.setText(_translate("MainWindow", "enregistrement fichier matieres"))
        self.actionrecuperation_fichier_matieres.setText(_translate("MainWindow", "recuperation fichier matieres"))
        self.actionenregistrement_fichier_notes.setText(_translate("MainWindow", "enregistrement fichier notes"))
        self.actionrecuperation_fichier_notes.setText(_translate("MainWindow", "recuperation fichier notes"))
#ouvrir fenetre ajout
   def ajoutEtud(self):
       Form = QtWidgets.QDialog()
       ui = ajoutForm()
       ui.setupUi(Form)
       ret = Form.exec_()


   #ouvrir fenetre supprimer
   def supprimer(self):
            Form = QtWidgets.QDialog()
            ui = supprimerForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_section(self):
             Form = QtWidgets.QDialog()
             ui = supprimer_sectionForm()
             ui.setupUi(Form)
             ret = Form.exec_()
   def supprimer_niveau(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_section_niveau(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_section_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()
    #ouvrir fenetre modifier
   def modifier_adresse(self):
            Form = QtWidgets.QDialog()
            ui = modifier_adresseForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_mail(self):
            Form = QtWidgets.QDialog()
            ui = modifier_mailForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_tel(self):
            Form = QtWidgets.QDialog()
            ui = modifier_telForm()
            ui.setupUi(Form)
            ret = Form.exec_()
    #affichage et recherche
   def recherche_niveau(self):
            Form = QtWidgets.QDialog()
            ui = recherche_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()

   def recherche_section(self):
            Form = QtWidgets.QDialog()
            ui = recherche_sectionForm()
            ui.setupUi(Form)
            ret = Form.exec_()

   def recherche_num(self):
            Form = QtWidgets.QDialog()
            ui = recherche_numForm()
            ui.setupUi(Form)
            ret = Form.exec_()

   def recherche_section_niveau(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()


        #gestion des matieres
   def ajout_matiere(self):
            Form = QtWidgets.QDialog()
            ui = ajout_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_coefficient_matiere(self):
            Form = QtWidgets.QDialog()
            ui = modifier_coefficient_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_nom_matiere(self):
            Form = QtWidgets.QDialog()
            ui = modifie_nom_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_code_matiere(self):
            Form = QtWidgets.QDialog()
            ui = recherche_code_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_section_matiere(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_section_semestre_matiere(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_semestre_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_matiere(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()

    #notes
   def ajout_note(self):
            Form = QtWidgets.QDialog()
            ui = ajout_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_note(self):
            Form = QtWidgets.QDialog()
            ui = modifier_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_num_inscr_note(self):
            Form = QtWidgets.QDialog()
            ui = recherche_num_inscr_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def rechercher_num_semestre_note(self):
            Form = QtWidgets.QDialog()
            ui = recherche_num_semestre_NOTEForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_section_niveau_note(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_niveau_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_note(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.show()
    sys.exit(app.exec_())
